const TRANSACTION_TYPE_AUTHORIZATION = 'authorization';
const TRANSACTION_TYPE_CAPTURE = 'capture';
const TRANSACTION_TYPE_REFUND = 'refund';
const TRANSACTION_TYPE_VOID = 'void';

module.exports = {
  TRANSACTION_TYPE_AUTHORIZATION,
  TRANSACTION_TYPE_CAPTURE,
  TRANSACTION_TYPE_REFUND,
  TRANSACTION_TYPE_VOID,
};
